-- ==============================================================================
-- SCRIPT 1: CREACIÓN DE BASE DE DATOS Y TABLAS
-- ==============================================================================

-- Nota: Asegúrate de estar conectado a tu base de datos destino (ej. 'matsso_db') antes de correr esto.

-- 1. Tabla original de Clientes (Se mantiene la estructura de Laravel)
CREATE TABLE IF NOT EXISTS public.clientes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(255) NOT NULL,
    cedula character varying(15) NOT NULL,
    telefono character varying(255),
    correo character varying(255),
    direccion text,
    fecha date NOT NULL DEFAULT CURRENT_DATE,
    ciudad character varying(255),
    lugar character varying(255),
    esquema character varying(255),
    tipo_examen character varying(255),
    puntaje_teorico character varying(255),
    puntaje_practico character varying(255),
    id_familia bigint,
    id_sector bigint,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP,
    nombre_examinador character varying(255),
    cedula_examinador character varying(20),
    telefono_examinador character varying(20),
    edad integer,
    celular1 character varying(20),
    cv_metadata json,
    CONSTRAINT clientes_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_cedula_unique UNIQUE (cedula)
);

-- 2. Tabla de Usuarios Web (Para el login del E-commerce)
-- Separamos las credenciales web de la tabla operativa de clientes.
CREATE TABLE IF NOT EXISTS public.usuarios_web
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cliente_id bigint, -- Relación con la tabla clientes de Laravel
    correo character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    rol character varying(50) NOT NULL DEFAULT 'ESTUDIANTE', -- ADMIN o ESTUDIANTE
    activo boolean DEFAULT true,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_web_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_web_correo_unique UNIQUE (correo),
    CONSTRAINT fk_usuario_cliente FOREIGN KEY (cliente_id)
        REFERENCES public.clientes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- 3. Tabla de Productos (Capacitaciones y Certificaciones)
CREATE TABLE IF NOT EXISTS public.productos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tipo character varying(50) NOT NULL, -- 'CAPACITACION' o 'CERTIFICACION'
    titulo character varying(255) NOT NULL,
    descripcion text,
    precio numeric(10,2) NOT NULL,
    horas integer,
    modalidad character varying(100), -- PRESENCIAL, ONLINE
    imagen_url character varying(255),
    activo boolean DEFAULT true,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
);

-- 4. Tabla de Esquemas de Certificación (Relacionado al producto)
CREATE TABLE IF NOT EXISTS public.esquemas_certificacion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    producto_id bigint NOT NULL,
    perfil_profesional character varying(255) NOT NULL,
    nombre_esquema character varying(255) NOT NULL,
    CONSTRAINT esquemas_pkey PRIMARY KEY (id),
    CONSTRAINT fk_esquema_producto FOREIGN KEY (producto_id)
        REFERENCES public.productos (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- 5. Tabla de Órdenes (Carritos pagados)
CREATE TABLE IF NOT EXISTS public.ordenes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint NOT NULL,
    total numeric(10,2) NOT NULL,
    estado character varying(50) NOT NULL DEFAULT 'PENDIENTE', -- PENDIENTE, COMPLETADO, CANCELADO
    fecha_orden timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP,
    metodo_pago character varying(100),
    CONSTRAINT ordenes_pkey PRIMARY KEY (id),
    CONSTRAINT fk_orden_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios_web (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 6. Tabla de Detalles de la Orden
CREATE TABLE IF NOT EXISTS public.orden_items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    orden_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    cantidad integer NOT NULL DEFAULT 1,
    CONSTRAINT orden_items_pkey PRIMARY KEY (id),
    CONSTRAINT fk_item_orden FOREIGN KEY (orden_id)
        REFERENCES public.ordenes (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_item_producto FOREIGN KEY (producto_id)
        REFERENCES public.productos (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
