<?php

/**
 * Catálogo canónico de variables documentales.
 *
 * `markers` contiene tanto el nombre normalizado como alias encontrados en las
 * plantillas originales. El servicio de documentos consume este archivo.
 */
return [
    'SECUENCIA_CODIGO' => ['label' => 'Secuencia del código', 'status' => 'available', 'markers' => ['SMD_secuencia_codigo']],
    'FECHA' => ['label' => 'Fecha del proceso', 'status' => 'available', 'markers' => ['FECHA', 'SMD_fecha']],
    'FECHA_C02' => ['label' => 'Fecha exclusiva del C02', 'status' => 'available', 'markers' => ['SMD_fecha_c02']],
    'NOMBRE' => ['label' => 'Nombre completo del candidato', 'status' => 'available', 'markers' => ['NOMBRE', 'SMD_nombrecompleto']],
    'CEDULA' => ['label' => 'Cédula del candidato', 'status' => 'available', 'markers' => ['CEDULA', 'SMD_cedula']],
    'CORREO' => ['label' => 'Correo del candidato', 'status' => 'available', 'markers' => ['CORREO', 'SMD_correo']],
    'EDAD' => ['label' => 'Edad del candidato', 'status' => 'available', 'markers' => ['SMD_edad']],
    'PROVINCIA' => ['label' => 'Provincia del candidato', 'status' => 'available', 'markers' => ['SMD_provincia']],
    'CIUDAD' => ['label' => 'Ciudad del candidato', 'status' => 'available', 'markers' => ['CIUDAD', 'SMD_ciudad', 'SMD_ciudaddesplegable']],
    'DIRECCION' => ['label' => 'Dirección del candidato', 'status' => 'available', 'markers' => ['DIRECCION', 'SMD_direccion']],
    'TELEFONO_CANDIDATO' => ['label' => 'Teléfono del candidato', 'status' => 'available', 'markers' => ['TELEFONO', 'SMD_telefono_candidato', 'SMD_telfono', 'SMD_telefono']],
    'CELULAR' => ['label' => 'Celular personal', 'status' => 'available', 'markers' => ['SMD_celular']],
    'PERFIL_PROFESIONAL' => ['label' => 'Perfil profesional', 'status' => 'available', 'markers' => ['SMD_perfil_profesional', 'SMD_Perfilprofecional', 'SMD_perfiles']],
    'ESQUEMA' => ['label' => 'Esquema de certificación', 'status' => 'available', 'markers' => ['ESQUEMA', 'SMD_esquema', 'SMD_esquemas']],
    'UNIDAD_COMPETENCIA_1' => ['label' => 'Unidad de competencia 1', 'status' => 'available', 'markers' => ['SMD_unidad_competencia_1']],
    'UNIDAD_COMPETENCIA_2' => ['label' => 'Unidad de competencia 2', 'status' => 'available', 'markers' => ['SMD_unidad_competencia_2']],
    'UNIDAD_COMPETENCIA_3' => ['label' => 'Unidad de competencia 3', 'status' => 'available', 'markers' => ['SMD_unidad_competencia_3']],
    'UNIDAD_COMPETENCIA_4' => ['label' => 'Unidad de competencia 4', 'status' => 'available', 'markers' => ['SMD_unidad_competencia_4']],
    'UNIDAD_COMPETENCIA_5' => ['label' => 'Unidad de competencia 5', 'status' => 'available', 'markers' => ['SMD_unidad_competencia_5', 'SMD_unidadesC']],
    'INSTALACIONES' => ['label' => 'Nombre de las instalaciones', 'status' => 'available', 'markers' => ['SMD_instalaciones', 'SMD_instalciones']],
    'DIRECCION_INSTALACION' => ['label' => 'Dirección de las instalaciones', 'status' => 'available', 'markers' => ['SMD_direccion_instalacion', 'SMD_direccion_instalaciones', 'SMD_direccionI']],
    'SECTOR_INSTALACION' => ['label' => 'Sector de las instalaciones', 'status' => 'available', 'markers' => ['SMD_sector', 'SMD_sector_instalaciones']],
    'TELEFONO_INSTALACION' => ['label' => 'Teléfono de las instalaciones', 'status' => 'available', 'markers' => ['SMD_telefono_instalacion', 'SMD_telefono_instalciones']],
    'EDUCACION_INSTITUCION' => ['label' => 'Institución de educación formal', 'status' => 'repeatable', 'markers' => ['SMD_educacion_institucion', 'SMD_nombreinstitución']],
    'EDUCACION_PAIS' => ['label' => 'País de educación formal', 'status' => 'repeatable', 'markers' => ['SMD_educacion_pais', 'SMD_educacion_paiz', 'SMD_pais_amano']],
    'EDUCACION_CIUDAD' => ['label' => 'Ciudad de educación formal', 'status' => 'repeatable', 'markers' => ['SMD_educacion_ciudad', 'SMD_ciudad_amano']],
    'EDUCACION_TITULO' => ['label' => 'Título obtenido', 'status' => 'repeatable', 'markers' => ['SMD_educacion_titulo', 'SMD_tituloobtenido']],
    'CAPACITACION_CURSO' => ['label' => 'Nombre del curso', 'status' => 'repeatable', 'markers' => ['SMD_capacitacion_curso']],
    'CAPACITACION_INSTITUCION' => ['label' => 'Institución o empresa de capacitación', 'status' => 'repeatable', 'markers' => ['SMD_capacitacion_institucion', 'SMD_capacitacion_instituto', 'SMD_nombreinstitucion']],
    'CAPACITACION_FECHA' => ['label' => 'Fecha de capacitación', 'status' => 'repeatable', 'markers' => ['SMD_capacitacion_fecha', 'SMD_fechacurso']],
    'CAPACITACION_HORAS' => ['label' => 'Horas de capacitación', 'status' => 'repeatable', 'markers' => ['SMD_capacitacion_horas', 'SMD_horas_curso', 'SMD_horas curso']],
    'EXPERIENCIA_FECHA_DESDE' => ['label' => 'Inicio de experiencia laboral', 'status' => 'repeatable', 'markers' => ['SMD_experiencia_fecha_desde', 'SMD_fechadesde']],
    'EXPERIENCIA_FECHA_HASTA' => ['label' => 'Fin de experiencia laboral', 'status' => 'repeatable', 'markers' => ['SMD_experiencia_fecha_hasta']],
    'EXPERIENCIA_EMPRESA' => ['label' => 'Empresa', 'status' => 'repeatable', 'markers' => ['SMD_experiencia_empresa', 'SMD_nombreEMP']],
    'EXPERIENCIA_CIUDAD' => ['label' => 'Ciudad o dirección de la empresa', 'status' => 'repeatable', 'markers' => ['SMD_experiencia_ciudad', 'SMD_ciudadEMP']],
    'EXPERIENCIA_TELEFONO' => ['label' => 'Teléfono de la empresa', 'status' => 'repeatable', 'markers' => ['SMD_experiencia_telefono', 'SMD_telefonoEMP']],
    'EXPERIENCIA_FUNCION' => ['label' => 'Función desempeñada', 'status' => 'repeatable', 'markers' => ['SMD_experiencia_funcion', 'SMD_funcionEMP']],
    'LUGAR_EXAMEN' => ['label' => 'Lugar de examinación', 'status' => 'available', 'markers' => ['LUGAR', 'SMD_lugar_examen', 'SMD_lugarcompleto']],
    'DIRECCION_EXAMEN' => ['label' => 'Dirección de examinación', 'status' => 'available', 'markers' => ['SMD_direccion_examen', 'SMD_restodedireccion']],
    'EXAMINADOR_NOMBRE' => ['label' => 'Nombre del examinador', 'status' => 'derived', 'markers' => ['SMD_nombreexaminador', 'SMD_Nombreexaminador', 'SMD_nombreexaminadordoc esquemas']],
    'EXAMINADOR_CEDULA' => ['label' => 'Cédula del examinador', 'status' => 'derived', 'markers' => ['SMD_cedulaexaminador']],
    'EXAMINADOR_TELEFONO' => ['label' => 'Teléfono del examinador', 'status' => 'derived', 'markers' => ['SMD_telefonoexaminador']],
    'CIUDAD_FECHA' => ['label' => 'Ciudad y fecha redactadas', 'status' => 'derived', 'markers' => ['SMD_ciudad_fecha', 'SMD_ciudaddesplegable+SMD_fecha']],
    'PUNTAJE_TEORICO' => ['label' => 'Puntaje teórico', 'status' => 'available', 'markers' => ['PUNTAJE_TEORICO', 'SMD_puntajeteorico']],
    'PUNTAJE_PRACTICO' => ['label' => 'Puntaje práctico', 'status' => 'available', 'markers' => ['PUNTAJE_PRACTICO', 'SMD_puntajepraactico']],
];
